Repository modern-agile-team/dongurami-front-v2, pull requests merged in 2023-11, with the labels that each got.

#8 feat(#7): jest 설정 및 테스트 코드 추가
  .github/pull_request_template.md
  .github/workflows/build.yaml
  .github/workflows/test.yaml
  jest.config.js
  jest.setup.ts
  package.json
  src/components/Column/Column.test.tsx
  src/components/Row/Row.test.tsx
  src/components/Row/Row.tsx
  src/components/SwitchCase/SwitchCase.test.tsx
  tsconfig.json
  yarn.lock
Labels: enhancement

#10 feat(#4): 게시판 템플릿 파일 생성
  src/containers/Board/InfinityScrollBoard/index.tsx
  src/containers/Board/PagenationBoard/emotion.ts
  src/containers/Board/PagenationBoard/index.tsx
  src/containers/Board/index.tsx
  src/pages/board/infinity/index.tsx
  src/pages/board/pagenation/index.tsx
Labels: enhancement

#11 feat(#2): WhatIF 컴포넌트 생성
  src/components/WhatIF/WhatIF.test.tsx
  src/components/WhatIF/WhatIF.tsx
  src/components/WhatIF/index.ts
  src/components/index.ts
  src/pages/index.tsx
Labels: enhancement

#12 feat(#7): storybook 초기 세팅
  .storybook/main.ts
  .storybook/preview.tsx
  package.json
  src/components/Button/Button.stories.ts
  src/components/Button/Button.tsx
  src/components/Button/emotion.ts
  src/containers/Board/InfinityScrollBoard/InfinityScrollBoard.stories.ts
  src/styles/color.ts
  yarn.lock
Labels: enhancement

#14 feat(#9): prettier 설치
  .prettierrc
  package.json
  yarn.lock
Labels: enhancement

#17 club 컨테이너 컴포넌트 추가
  src/containers/club/Activity/Activity.tsx
  src/containers/club/Activity/index.ts
  src/containers/club/Apply/Apply.tsx
  src/containers/club/Apply/index.ts
  src/containers/club/Home/Home.tsx
  src/containers/club/Home/index.ts
  src/containers/club/Notice/Notice.tsx
  src/containers/club/Notice/index.ts
  src/containers/club/Review/Review.tsx
  src/containers/club/Review/index.ts
  src/containers/club/Schedule/Schedule.tsx
  src/containers/club/Schedule/index.ts
  src/containers/club/index.ts
  src/containers/index.ts
  src/pages/club/[clubID].tsx
  src/styles/globals.css
Labels: enhancement

#19 feat(#4): 게시판 템플릿 레이아웃 작업
  package.json
  src/components/Grid/Grid.tsx
  src/containers/Board/InfinityScrollBoard/InfinityScrollBoard.stories.ts
  src/containers/Board/InfinityScrollBoard/InfinityScrollBoard.tsx
  src/containers/Board/InfinityScrollBoard/emotion.ts
  src/containers/Board/InfinityScrollBoard/index.ts
  src/containers/Board/InfinityScrollBoard/index.tsx
  src/containers/Board/PagenationBoard/PagenationBoard.tsx
  src/containers/Board/PagenationBoard/emotion.ts
  src/containers/Board/PagenationBoard/index.ts
  src/containers/Board/PagenationBoard/index.tsx
  src/containers/Board/index.tsx
  yarn.lock
Labels: enhancement

#22 feat(#4): react-Query 적용 api 연동 test
  package.json
  src/components/Provider/DonguramiProvider.tsx
  src/containers/Board/InfinityScrollBoard/InfinityScrollBoard.tsx
Labels: ✨ Feature

#27 feat(#QYOG-12): 로그인 페이지
  src/__test__/Login.test.tsx
  src/containers/Login/Form/Form.tsx
  src/containers/Login/Form/emotion.ts
  src/containers/Login/Form/index.ts
  src/containers/Login/Layout/Layout.tsx
  src/containers/Login/Layout/index.ts
  src/containers/Login/index.ts
  src/containers/index.ts
  src/pages/index.tsx
  src/pages/login/index.tsx
Labels: ✨ Feature

#28 feat(QYOG-18): generate-api 참조 위치를 스웨거 서버로 변경
  api.json
  scripts/generate-api.js
  src/@types/apis/Apis.d.ts
Labels: ⚙️ Configuration, 🤝 API
