Repository modern-agile-team/dongurami-front-v2, pull requests merged in 2024-05, with the labels that each got.

#79 fix(QYOG-145): tab 예외처리로직, 변경로직 위치 변경
  src/__test__/Club.test.tsx
  src/containers/Club/Sidebar/Sidebar.tsx
  src/pages/club/[clubID].tsx
Labels: 🐞 Bug Fix

#81 feat(QYOG-153): 동아리 검색 개선
  src/components/UI/Club/Card/Card.tsx
  src/components/UI/Club/List/List.tsx
  src/hooks/clubList/index.ts
  src/hooks/clubList/useAllClubCategories/index.ts
  src/hooks/clubList/useAllClubCategories/useAllClubCategories.ts
  src/hooks/clubList/useClubList/index.ts
  src/hooks/clubList/useClubList/useClubList.ts
Labels: ✨ Feature, 🤝 API

#80 Feat(QYOG-125): 일반 게시글 alert 생성
  src/@types/emotion.d.ts
  src/assets/svg/chat_30.svg
  src/assets/svg/deletion_32.svg
  src/assets/svg/good_32.svg
  src/assets/svg/notice_32.svg
  src/assets/svg/pan_35.svg
  src/assets/svg/warning_32.svg
  src/components/Svg/Icons/chat-30.tsx
  src/components/Svg/Icons/deletion-32.tsx
  src/components/Svg/Icons/good-32.tsx
  src/components/Svg/Icons/index.ts
  src/components/Svg/Icons/notice-32.tsx
  src/components/Svg/Icons/pan-35.tsx
  src/components/Svg/Icons/warning-32.tsx
  src/components/UI/Alert/Alert.tsx
  src/components/UI/Alert/emotion.ts
  src/components/UI/Alert/index.ts
  src/components/UI/Board/Comment/Comment.tsx
  src/components/UI/Board/Comment/emotion.ts
  src/containers/Board/DetailBoard/DetailBoard.tsx
  src/containers/Board/DetailBoard/emotion.ts
  src/containers/Board/WriteBoard/WriteBoard.tsx
  src/styles/theme/typography.ts
Labels: ✨ Feature
