Repository modern-agile-team/dongurami-front-v2, pull requests merged in 2024-02, with the labels that each got.

#54 feat(QYOG-53): 자유, 공지 테이블 컴포넌트 추가
  src/@types/emotion.d.ts
  src/assets/board/left.png
  src/assets/board/right.png
  src/assets/main/logo.png
  src/components/UI/Header/Header.tsx
  src/components/UI/Header/emotion.ts
  src/components/UI/Header/index.ts
  src/components/UI/Pagination/Pagination.tsx
  src/components/UI/Pagination/emotion.ts
  src/components/UI/Table/Table.tsx
  src/components/UI/Table/emotion.ts
  src/components/UI/Table/index.ts
  src/containers/Board/SearchWriter/SearchWriter.tsx
  src/containers/Board/SearchWriter/emotion.ts
  src/containers/Board/SearchWriter/index.ts
  src/pages/_app.tsx
  src/pages/board/free/index.tsx
  src/pages/board/notice/index.tsx
  src/pages/index.tsx
  src/styles/theme/color.ts
Labels: ✨ Feature, 🔨 Refactor

#57 feat(QYOG-79): 홈 화면 동아리 미리보기
  src/components/Svg/Svg.tsx
  src/components/Svg/index.ts
  src/components/UI/Header/Header.tsx
  src/components/UI/TextField/TextField.tsx
  src/components/UI/TextField/emotion.ts
  src/components/UI/TextField/index.ts
  src/components/UI/index.ts
  src/containers/Home/ClubPreview/ClubPreview.tsx
  src/containers/Home/ClubPreview/index.ts
  src/containers/Home/index.ts
  src/pages/index.tsx
Labels: ✨ Feature, 🐞 Bug Fix

#61 feat(QYOG-79): 모집중인 동아리 UI
  .github/workflows/test.yaml
  jest.config.js
  package.json
  src/@types/next-image.d.ts
  src/components/UI/Footer/Footer.tsx
  src/components/UI/Footer/index.ts
  src/components/UI/Header/Header.tsx
  src/components/UI/Header/emotion.ts
  src/components/UI/index.ts
  src/containers/Home/ClubPreview/ClubPreview.tsx
  src/containers/Home/RecruitingClubs/RecruitingClubs.tsx
  src/containers/Home/RecruitingClubs/index.ts
  src/containers/Home/index.ts
  src/pages/_app.tsx
  src/pages/index.tsx
  src/utils/converter/converter.ts
  src/utils/converter/index.ts
  src/utils/index.ts
  tsconfig.json
  yarn.lock
Labels: ✨ Feature

#62 SVGR(QYOG-86): svgr 고도화
  package.json
  plugins/svg-dynamic-title-plugin.js
  plugins/svg-remove-fill-pluigin.js
  plugins/svg-replace-plugin.js
  src/assets/board/left.png
  src/assets/board/right.png
  src/assets/svg/chat_24.svg
  src/assets/svg/check_35.svg
  src/assets/svg/heart_24.svg
  src/assets/svg/heart_full_24.svg
  src/assets/svg/left-arrow_24.svg
  src/assets/svg/right-arrow_24.svg
  src/assets/svg/search_30.svg
  src/components/Svg/Icon.tsx
  src/components/Svg/Icons/chat-24.tsx
  src/components/Svg/Icons/check-35.tsx
  src/components/Svg/Icons/heart-24.tsx
  src/components/Svg/Icons/heart-full-24.tsx
  src/components/Svg/Icons/index.ts
  src/components/Svg/Icons/left-arrow-24.tsx
  src/components/Svg/Icons/right-arrow-24.tsx
  src/components/Svg/Icons/search-30.tsx
  src/components/Svg/Svg.tsx
  src/components/Svg/index.ts
  src/components/Svg/type.ts
  src/components/UI/Pagination/Pagination.tsx
  src/containers/Home/ClubPreview/ClubPreview.tsx
  src/pages/board/free/index.tsx
  src/pages/board/notice/index.tsx
  src/utils/filterHTMLAttribute/filterHTMLAttribute.ts
  svgr.config.js
  yarn.lock
Labels: ✨ Feature, 🎁 package, ⚙️ Configuration

#63 feat(QYOG-89): 게시판 조회 방식 수정
  src/components/UI/Header/Header.tsx
  src/components/UI/Loader/Loader.tsx
  src/components/UI/Loader/index.ts
  src/components/UI/index.ts
  src/pages/board/free/index.tsx
  src/pages/board/notice/index.tsx
  src/pages/club/[clubID].tsx
Labels: ✨ Feature

#64 feat(QYOG-91): 동아리 홈 탭 UI
  next.config.js
  package.json
  src/__test__/Club.test.tsx
  src/components/UI/Footer/Footer.tsx
  src/components/UI/Header/emotion.ts
  src/containers/Club/Home/Home.tsx
  src/containers/Club/Home/components/Information/Information.tsx
  src/containers/Club/Home/components/Information/emotion.ts
  src/containers/Club/Home/components/Information/index.ts
  src/containers/Club/Home/components/index.ts
  src/containers/Club/Sidebar/Sidebar.tsx
  src/containers/Club/Sidebar/emotion.ts
  src/containers/Club/Sidebar/index.ts
  src/containers/Club/index.ts
  src/pages/api/openai/image.ts
  src/pages/club/[clubID].tsx
  yarn.lock
Labels: ✨ Feature
